using Microsoft.EntityFrameworkCore;
using PCA.Modules.Documents.Models;
using PCA.Modules.Documents.Services;
using PCA.Modules.Identity.Models;
using PCA.Modules.Invoicing.Services;
using PCA.Shared.Enums;
using PCA.Web.Data;

namespace PCA.Web.Services;

public class InvoiceDocumentRegistrar : IInvoiceDocumentRegistrar
{
    private readonly IDocumentService _docs;
    private readonly ApplicationDbContext _db;

    public InvoiceDocumentRegistrar(IDocumentService docs, ApplicationDbContext db)
    {
        _docs = docs;
        _db   = db;
    }

    public async Task RegisterAsync(
        string filePath,
        string lenderName,
        string monthYear,
        int scheduleId,
        string scheduleName,
        string? triggeredById)
    {
        var folderId = await EnsureInvoicesFolderAsync();
        var fileName = Path.GetFileName(filePath);
        var fileInfo = new FileInfo(filePath);

        var doc = new Document
        {
            Title       = $"Invoice — {lenderName} — {monthYear}",
            Description = $"Auto-generated invoice for schedule '{scheduleName}' ({monthYear}).",
            Tags        = $"invoice,{lenderName},{monthYear}",
            FolderId    = folderId,
            OwnerId     = triggeredById ?? await GetSystemUserIdAsync(),
            CreatedById = triggeredById ?? await GetSystemUserIdAsync(),
            Status      = DocumentStatus.Active
        };

        await _docs.RegisterExistingFileAsync(
            doc,
            filePath,
            fileName,
            fileInfo.Exists ? fileInfo.Length : 0,
            $"Auto-generated by invoice run for schedule '{scheduleName}'");
    }

    private async Task<int?> EnsureInvoicesFolderAsync()
    {
        var existing = await _db.DocumentFolders
            .FirstOrDefaultAsync(f => f.Name == "Invoices" && f.ParentId == null);

        if (existing != null)
            return existing.Id;

        var systemUserId = await GetSystemUserIdAsync();
        var folder = await _docs.CreateFolderAsync(new DocumentFolder
        {
            Name        = "Invoices",
            Description = "Auto-generated invoice files",
            CreatedById = systemUserId
        });

        return folder.Id;
    }

    private async Task<string> GetSystemUserIdAsync()
    {
        var admin = await _db.Users.FirstOrDefaultAsync(u => u.Email == "admin@pca.local");
        return admin?.Id ?? string.Empty;
    }
}
